// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjYYFhVdxR_2UiH2C4YN7EtDXf6EOcCso',
    appId: '1:782307887616:web:d0e3657b514335da1f66e5',
    messagingSenderId: '782307887616',
    projectId: 'untzi-demo',
    authDomain: 'untzi-demo.firebaseapp.com',
    storageBucket: 'untzi-demo.appspot.com',
    measurementId: 'G-QT9ZEFKRVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAupayuMXlisHZTmsiHlhT_A5cXGtb2lCM',
    appId: '1:782307887616:android:6874eb7b521e59541f66e5',
    messagingSenderId: '782307887616',
    projectId: 'untzi-demo',
    storageBucket: 'untzi-demo.appspot.com',
  );
}
